### ISSUE TITLE
Simulate the "waiting for response" behavior

### ISSUE THREAD

**Issue by ogaston** [rmariuzzo/fotch#8]
Hi @rmariuzzo 

Hope you doing well. This repo looks quite handy to me for testing components that request server data (even when such server/endpoint doesn't exist yet).

**Have you considered adding a fake time of waiting for the response?** If so, let me know, and I make a proposal right here and afterward a pull-request.

**Comment by rmariuzzo** [comment]
> **Have you considered adding a fake time of waiting for the response?** If so, let me know, and I make a proposal right here and afterward a pull-request.

Yes, @ogaston I have been considering this, that will be a good feature to have in it.

**Comment by ogaston** [comment]
Great!

So, right now the **start** method is just receiving one string parameter, This would be a good opportunity to overload that method to use this parameter as an options object too.

```javascript
fotch.start({
  match: '/api/',
  waitingTime: 200 // milliseconds
})
```

What do you think?

**Comment by rmariuzzo** [comment]
Sounds like a good idea. I'm thinking on accepting different parameters such as:
```ts
type FotchOptions = {
  start: string
  delay: number | [min: number, max: number]
}
```

The `delay` (which corresponds to your `waitingTime`) will accept a constant delay in ms or a range (min/max) to simulate latency.

What do you think?

**Comment by rmariuzzo** [comment]
#9
